export const Movies = [
"El resplandor",
"Letras Explicitas",
"Alien",
"Volver al futuro",
"Dragon Ball Z",
"Actividad Paranormal",
"Tiburon",
"Karate Kid",
"Pixeles",
"Jurassic World",
"Toy Story",
"La era de hielo",
"Transformers",
"El Hobbit",
"La mascara",
"Indiana Jones",
"Ghost Rider",
"Los Juegos del Hambre",
"Hombres de Negro",
"Ouija",
"Space Jam",
"Buscando a Nemo",
"Solo por dinero",
"Sinsajo Parte",
"Sin limites",
"Sin escape",
"Sin nombre",
"Los 4 fantasticos",
"Max",
"Vacaciones",
"Mision Imposible",
"Los Vengadores",
"Lugares Oscuros",
"Bajo el mismo cielo (Aloha)",
"Antes de ir",
"El regalo",
"Chica Final",
"Chappie",
"Kingsman, el servicio secreto",
"El invitado",
"Dracula",
"Resident Evil",
"Mi novio es un Zombie",
"Guerra Mundial Z",
"Terror en Silent Hill",
"Carrie",
"Diabolica tentacion",
"Esta detras de ti",
"Una pelicula de miedo",
"Archivo 253",
"Palabras Diabolicas",
"Pesadilla en la calle Elm",
"Siniestro",
"Mama",
"Dama de Negro",
"Sangre de mi sangre",
"Caso 39",
"The Ouija Experimenet",
"La huerfana",
"Chucky, el muneco diabolico",
"Actividad Paranormal",
"La cabana del terror",
"Nuestro ultimo verano en Escocia",
"Verano en Staten Island",
"Todo es relativo",
"Amor de mis amores",
"La dictadura perfecta",
"La peor noche de mi vida",
"Heroe de centro comercial",
"¿Y, donde estan las rubias?",
"Ese es mi hijo",
"Son como ninos",
"Este cuerpo no es mio",
"Jack y Jill",
"Todo un parto",
"Los juegos hambrientos",
"Nacho Libre",
"Norbit",
"Pelotas en juego",
"Una pareja de idiotas",
"Golpe bajo",
"Mi villano favorito",
"El dador de recuerdos",
"El secreto de Adaline",
"John Carter",
"Astro Boy",
"Los Pinguinos de Madagascar",
"Hombres de negro",
"El planeta del tesoro",
"Atlantis El imperio perdido",
"Los Vengadores",
"Iron Man",
"Gigantes de acero",
"Megamente",
"Super 8",
"Guerra de los mundos",
"Sector 9",
"Wall-E",
"El planeta de los simios",
"Tron",
"Recuerda este domingo",
"La vida segura Grata",
"Amor de Verano",
"Si decido quedarme",
"3 metros sobre el cielo",
"Donde el corazon te lleva",
"Lecho de hielo",
"Secuestradores",
"La ventajas de ser invisible",
"Operacion regalo",
"Siempre Alice",
"Una buena mentira",
"El codigo enigma",
"Orgullo y prejuicio",
"Duelo de titanes",
"Historias cruzadas",
"Un sueno imposible",
"Belleza Americana",
"Suenos en fuga",
"Preciosa",
"Bajo el mismo techo",
"La ultima cancion",
"Querido John",
"Amigos con derecho",
"Love, Rosie",
"Lo mejor de mi",
"Un pedacito de cielo",
"En tus ojos",
"La vida segun Greta",
"6 años",
"Eterna juventud",
"Escribiendo de amor",
"Amigos intocables",
"Las horas contigo",
"Luna nueva",
"Tributo a mi madre",
"Recuerdame",
"Diario de una pasion",
"La dama de oro",
"Alienigenas Ancestrales y el Bigfoot",
"Osos",
"Azul intangible",
"Hijos de las nubes La ultima colonia",
"Titanes de la Era de Hielo",
"Indignados",
"Torre de marfil",
"Happy Valley",
"Solo Escalada a la vida",
"El color que cayo del cielo",
"En tierra extrana",
"Los ojos de America",
"Eco de la montana",
"El refugio",
"Al fin del mundo",
"Muros",
"Lucha por el patrimonio",
"En los ojos de la memoria",
"Francisco",
"Bill",
"En busca de la felicidad",
"Maradona, la mano de Dios",
"Cleopatra",
"El solista",
"Sin limites",
"Ali",
"Sugar",
"Howl",
"Notorious",
"Amelia",
"Gandhi",
"12 años de esclavitud",
"Shine",
]
export const Countries =
["Afganistán",
"Albania",
"Alemania",
"Andorra",
"Angola",
"Antigua y Barbuda",
"Arabia Saudita",
"Argelia",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaiyán",
"Bahamas",
"Bahréin",
"Bangladés",
"Barbados",
"Bielorrusia",
"Bélgica",
"Belice",
"Benín",
"Bután",
"Bolivia",
"Bosnia-Herzegovina",
"Botsuana",
"Brasil",
"Brunéi",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cabo Verde",
"Camboya",
"Camerún",
"Canadá",
"Chad",
"República Checa",
"Chequia",
"Chile",
"China",
"Chipre",
"Colombia",
"Comoras",
"Congo",
"República Democrática del Congo",
"Corea del Norte",
"Corea del Sur",
"Costa Rica",
"Costa de Marfil",
"Croacia",
"Cuba",
"Dinamarca",
"Yibuti",
"Dominica",
"Ecuador",
"Egipto",
"El Salvador",
"Emiratos Árabes Unidos",
"Eritrea",
"Eslovaquia",
"Eslovenia",
"España",
"Estados Unidos",
"Estonia",
"Etiopía",
"Fiyi",
"Filipinas",
"Finlandia",
"Francia",
"Gabón",
"Gambia",
"Georgia",
"Ghana",
"Granada",
"Grecia",
"Guatemala",
"Guinea",
"Guinea-Bissau",
"Guinea Ecuatorial",
"Guyana",
"Haití",
"Honduras",
"Hungría",
"India",
"Indonesia",
"Irán",
"Iraq",
"Irlanda",
"Islandia",
"Israel",
"Italia",
"Jamaica",
"Japón",
"Jordania",
"Kazajistán",
"Kenia",
"Kirguistán",
"Kiribati",
"Kuwait",
"Laos",
"Lesoto",
"Letonia",
"Líbano",
"Liberia",
"Libia",
"Liechtenstein",
"Lituania",
"Luxemburgo",
"Macedonia",
"Madagascar",
"Malasia",
"Malaui",
"Maldivas",
"Mali",
"Malta",
"Marruecos",
"Islas Marshall",
"Mauricio",
"Mauritania",
"México",
"Micronesia",
"Moldavia",
"Mónaco",
"Mongolia",
"Montenegro",
"Mozambique",
"Birmania",
"Namibia",
"Nauru",
"Nepal",
"Nicaragua",
"Níger",
"Nigeria",
"Noruega",
"Nueva Zelanda",
"Omán",
"Países Bajos",
"Pakistán",
"Palaos",
"Panamá",
"Papúa Nueva Guinea",
"Paraguay",
"Perú",
"Polonia",
"Portugal",
"Qatar",
"Reino Unido",
"República Centroafricana",
"República Dominicana",
"Rumania",
"Rusia",
"Ruanda",
"San Cristóbal y Nieves",
"Islas Salomón",
"Samoa",
"San Marino",
"Santa Lucía",
"Ciudad del Vaticano",
"Santo Tomé y Príncipe",
"San Vicente y las Granadinas",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leona",
"Singapur",
"Siria",
"Somalia",
"Sri Lanka",
"Sudáfrica",
"Sudán",
"Sudán del Sur",
"Suecia",
"Suiza",
"Surinam",
"Suazilandia",
"Tailandia",
"Tanzania",
"Tayikistán",
"Timor Oriental",
"Togo",
"Tonga",
"Trinidad y Tobago",
"Túnez",
"Turkmenistán",
"Turquía",
"Tuvalu",
"Ucrania",
"Uganda",
"Uruguay",
"Uzbekistán",
"Vanuatu",
"Venezuela",
"Vietnam",
"Yemen",
"Zambia",
"Zimbabue"]

export const Misscelaneous =
[
    "humanidad",
    "humano",
    "persona",
    "gente",
    "hombre",
    "mujer",
    "bebé",
    "niño",
    "niña",
    "adolescente",
    "adulto",
    "adulta",
    "anciano",
    "anciana",
    "don",
    "doña",
    "señor",
    "señora",
    "caballero",
    "dama",
    "individuo",
    "cuerpo",
    "pierna",
    "pie",
    "talón",
    "espinilla",
    "rodilla",
    "muslo",
    "cabeza",
    "cara",
    "boca",
    "labio",
    "diente",
    "ojo",
    "nariz",
    "barba",
    "bigote",
    "cabello",
    "oreja",
    "cerebro",
    "estómago",
    "brazo",
    "codo",
    "hombro",
    "uña",
    "mano",
    "muñeca",
    "palma",
    "dedo",
    "trasero",
    "culo",
    "cola",
    "glúteos",
    "abdomen",
    "hígado",
    "músculo",
    "cuello",
    "corazón",
    "mente",
    "alma",
    "espíritu",
    "pecho",
    "cintura",
    "cadera",
    "espalda",
    "sangre",
    "carne",
    "piel",
    "hueso",
    "resfriado",
    "gripe",
    "diarrea",
    "salud",
    "enfermedad",
    "familia",
    "amigo",
    "amiga",
    "conocido",
    "conocida",
    "colega",
    "pareja",
    "esposo",
    "esposa",
    "matrimonio",
    "amor",
    "padre",
    "madre",
    "hermano",
    "hermana",
    "hijo",
    "hija",
    "abuelo",
    "abuela",
    "bisabuelo",
    "bisabuela",
    "nieto",
    "nieta",
    "bisnieto",
    "bisnieta",
    "primo",
    "prima",
    "tío",
    "tía",
    "sobrino",
    "sobrina",
    "criatura",
    "especie",
    "ser",
    "vida",
    "nacimiento",
    "reproducción",
    "muerte",
    "naturaleza",
    "campo",
    "bosque",
    "selva",
    "jungla",
    "desierto",
    "costa",
    "playa",
    "río",
    "laguna",
    "lago",
    "mar",
    "océano",
    "cerro",
    "monte",
    "montaña",
    "luz",
    "energía",
    "animal",
    "perro",
    "gato",
    "vaca",
    "cerdo",
    "caballo",
    "yegua",
    "oveja",
    "mono",
    "ratón",
    "rata",
    "tigre",
    "conejo",
    "dragón",
    "ciervo",
    "rana",
    "león",
    "jirafa",
    "elefante",
    "pájaro",
    "gallina",
    "gorrión",
    "cuervo",
    "águila",
    "halcón",
    "pez",
    "camarón",
    "langosta",
    "sardina",
    "atún",
    "calamar",
    "pulpo",
    "insecto",
    "bicho",
    "mariposa",
    "polilla",
    "saltamontes",
    "araña",
    "mosca",
    "mosquito",
    "cucaracha",
    "caracol",
    "babosa",
    "lombriz",
    "marisco",
    "molusco",
    "lagarto",
    "serpiente",
    "cocodrilo",
    "alimento",
    "comida",
    "bebida",
    "vegetal",
    "planta",
    "pasto",
    "césped",
    "flor",
    "fruta",
    "semilla",
    "árbol",
    "hoja",
    "raíz",
    "tallo",
    "hongo",
    "ciruela",
    "pino",
    "bambú",
    "nuez",
    "almendra",
    "castaña",
    "arroz",
    "avena",
    "cebada",
    "trigo",
    "verdura",
    "patatas",
    "papas",
    "judías",
    "guisantes",
    "porotos",
    "rábano",
    "zanahoria",
    "manzana",
    "naranja",
    "plátano",
    "pera",
    "castaño",
    "durazno",
    "tomate",
    "sandía",
    "carne",
    "gaseosa",
    "tiempo",
    "calendario",
    "edad",
    "época",
    "era",
    "fecha",
    "instante",
    "momento",
    "segundo",
    "minuto",
    "hora",
    "día",
    "semana",
    "entre semana",
    "fin de semana",
    "mes",
    "año",
    "década",
    "siglo",
    "milenio",
    "ayer",
    "hoy",
    "mañana",
    "amanecer",
    "mediodía",
    "tarde",
    "anochecer",
    "noche",
    "lunes",
    "martes",
    "miércoles",
    "jueves",
    "viernes",
    "sábado",
    "domingo",
    "ambiente",
    "espacio",
    "entorno",
    "área",
    "superficie",
    "volumen",
    "región",
    "zona",
    "lado",
    "mundo",
    "planeta",
    "sol",
    "luna",
    "estrella",
    "galaxia",
    "universo",
    "clima",
    "despejado",
    "nublado",
    "lluvia",
    "nieve",
    "viento",
    "trueno",
    "rayo",
    "tormenta",
    "cielo",
    "este",
    "oeste",
    "sur",
    "norte",
    "derecha",
    "izquierda",
    "diagonal",
    "exterior",
    "interior",
    "calor",
    "agua",
    "hielo",
    "vapor",
    "fuego",
    "gas",
    "aire",
    "atmósfera",
    "tierra",
    "piso",
    "suelo",
    "metal",
    "metálico",
    "hierro",
    "oro",
    "plata",
    "plomo",
    "sal",
    "barro",
    "lodo",
    "peso",
    "metro",
    "milímetro",
    "centímetro",
    "kilómetro",
    "litro",
    "gramo",
    "kilo",
    "cantidad",
    "total",
    "medida",
    "sociedad",
    "comunidad",
    "reunión",
    "encuentro",
    "estructura",
    "administración",
    "organización",
    "asociación",
    "empresa",
    "equipo",
    "autoridad",
    "cargo",
    "campaña",
    "club",
    "comisión",
    "congreso",
    "consejo",
    "partido",
    "país",
    "nación",
    "gobierno",
    "estado",
    "provincia",
    "departamento",
    "municipio",
    "democracia",
    "dictadura",
    "política",
    "político",
    "presidente",
    "ministro",
    "director",
    "parlamentario",
    "congresista",
    "senador",
    "diputado",
    "representante",
    "gobernador",
    "intendente",
    "alcalde",
    "policía",
    "bomberos",
    "capital",
    "ciudad",
    "población",
    "pueblo",
    "villa",
    "obligación",
    "libertad",
    "derecho",
    "permiso",
    "prohibición",
    "constitución",
    "ley",
    "decreto",
    "norma",
    "economía",
    "consumo",
    "demanda",
    "compañía",
    "comercio",
    "mercado",
    "servicio",
    "producto",
    "producción",
    "transacción",
    "almacén",
    "hotel",
    "fábrica",
    "cuenta",
    "boleto",
    "entrada",
    "dinero",
    "billete",
    "vuelto",
    "cambio",
    "máquina expendedora",
    "precio",
    "tarifa",
    "valor",
    "escritorio",
    "silla",
    "mesa",
    "cama",
    "dormitorio",
    "habitación",
    "cuarto",
    "oficina",
    "panel",
    "puerta",
    "ventana",
    "entrada",
    "hogar",
    "casa",
    "apartamento",
    "departamento",
    "edificio",
    "construcción",
    "elevador",
    "ascensor",
    "escalera",
    "aparato",
    "cámara",
    "aguja",
    "clavo",
    "hilo",
    "cuerda",
    "cordel",
    "cordón",
    "bolsillo",
    "bolso",
    "bolsa",
    "paraguas",
    "parasol",
    "pantalla",
    "pomo",
    "llave",
    "trancar",
    "arma",
    "escultura",
    "libro",
    "revista",
    "cuadro",
    "grabado",
    "electricidad",
    "corriente",
    "base",
    "pata",
    "conexión",
    "ropa",
    "prenda",
    "manga",
    "solapa",
    "cuello",
    "botón",
    "cremallera",
    "cierre",
    "cinturón",
    "zapato",
    "gafas",
    "pantalón",
    "camisa",
    "camiseta",
    "zapatilla",
    "cordones",
    "abrigo",
    "chaqueta",
    "calcetines",
    "bragas",
    "calzón",
    "calzoncillo",
    "sujetador",
    "sostén",
    "falda",
    "transporte",
    "transporte público",
    "transporte privado",
    "tránsito",
    "tráfico",
    "vehículo",
    "tren",
    "ferrocarril",
    "subterráneo",
    "metro",
    "camino",
    "vía",
    "ruta",
    "calle",
    "carretera",
    "autopista",
    "avenida",
    "estación",
    "parada",
    "avión",
    "aeropuerto",
    "automóvil",
    "coche",
    "auto",
    "bus",
    "autobús",
    "ómnibus",
    "ambulancia",
    "número",
    "alfabeto",
    "símbolo",
    "punto",
    "coma",
    "raíz",
    "origen",
    "fuente",
    "papel",
    "carta",
    "comunicación",
    "expresión",
    "voz",
    "texto",
    "periodismo",
    "periódico",
    "diario",
    "diccionario",
    "documento",
    "informe",
    "noticia",
    "computadora",
    "ordenador",
    "idioma extranjero",
    "japonés",
    "inglés",
    "chino",
    "alemán",
    "español",
    "francés",
    "color",
    "blanco",
    "negro",
    "gris",
    "rojo",
    "naranja",
    "anaranjado",
    "amarillo",
    "verde",
    "celeste",
    "azul",
    "violeta",
    "rosa",
    "rosado",
    "marrón",
    "café",
    "cultura",
    "autor",
    "actuación",
    "espectador",
    "espectáculo",
    "entretenimiento",
    "arte",
    "cine",
    "dibujo",
    "pintura",
    "música",
    "religión",
    "dios",
    "artículo",
    "educación",
    "escuela",
    "instituto",
    "colegio",
    "universidad",
    "clase",
    "curso",
    "estudio",
    "formación",
    "análisis",
    "investigación",
    "conocimiento",
    "idea",
    "información",
    "dato",
    "forma",
    "manera",
    "modo",
    "estilo",
    "figura",
    "elemento",
    "uso",
    "utilización",
    "ciencia",
    "aritmética",
    "historia",
    "geografía",
    "educación física",
    "deporte",
    "carrera",
    "competición",
    "competencia",
    "ayuda",
    "favor",
    "apoyo",
    "búsqueda",
    "duda",
    "pregunta",
    "respuesta",
    "cuestión",
    "solicitud",
    "decisión",
    "elección",
    "consejo",
    "sugerencia",
    "orden",
    "control",
    "sistema",
    "trabajo",
    "empleo",
    "profesión",
    "esfuerzo",
    "cero",
    "uno",
    "dos",
    "tres",
    "cuatro",
    "cinco",
    "seis",
    "siete",
    "ocho",
    "nueve",
    "diez",
    "cien",
    "ciento",
    "mil",
    "millón",
    "lugar",
    "posición",
    "movimiento",
    "velocidad",
    "aceleración",
    "dirección",
    "tamaño",
    "largo",
    "longitud",
    "alto",
    "altura",
    "ancho",
    "mayoría",
    "minoría",
    "aumento",
    "reducción",
    "crecimiento",
    "fondo",
    "frente",
    "cosa",
    "aspecto",
    "contenido",
    "objeto",
    "parte",
    "sector",
    "palabra",
    "nombre",
    "código",
    "secreto",
    "formalidad",
    "presente",
    "pasado",
    "futuro",
    "ocasión",
    "vez",
    "acción",
    "actividad",
    "acto",
    "programa",
    "proyecto",
    "obra",
    "acuerdo",
    "actitud",
    "atención",
    "capacidad",
    "concepto",
    "tema",
    "condición",
    "caso",
    "conjunto",
    "grupo",
    "creación",
    "destrucción",
    "origen",
    "destino",
    "objetivo",
    "meta",
    "función",
    "relación",
    "realidad",
    "situación",
    "problema",
    "intento",
    "solución",
    "efecto",
    "resultado",
    "logro",
    "éxito",
    "fracaso",
    "causa",
    "consecuencia",
    "beneficio",
    "perjuicio",
    "calidad",
    "tipo",
    "ataque",
    "defensa",
    "paz",
    "conflicto",
    "guerra",
    "carácter",
    "característica",
    "crisis",
    "cambio",
    "desarrollo",
    "progreso",
    "avance",
    "retroceso",
    "mejora",
    "deterioro",
    "comienzo",
    "inicio",
    "principio",
    "transcurso",
    "fin",
    "final",
    "cabo",
    "etapa",
    "fase",
    "paso",
    "serie",
    "secuencia",
    "grado",
    "nivel",
    "proceso",
    "corte",
    "interrupción",
    "espera",
    "diferencia",
    "similitud",
    "sentido",
    "sensación",
    "vista",
    "oído",
    "tacto",
    "olfato",
    "dolor",
    "conciencia",
    "percepción",
    "imagen",
    "fuerza",
    "potencia",
    "presencia",
    "existencia",
    "experiencia",
    "posibilidad",
    "probabilidad",
    "verdad",
    "mentira",
    "razón",
    "acierto",
    "equivocación",
    "necesidad",
    "falta",
    "significado",
    "carácter",
    "personalidad",
    "pensamiento",
    "memoria",
    "recuerdo",
    "deseo",
    "alegría",
    "tristeza",
    "enojo",
    "enfado",
    "placer",
    "éxtasis",
    "empatía",
    "interés",
    "aburrimiento",
    "cansancio",
    "sorpresa",
    "susto",
    "seguridad",
    "confianza",
    "miedo",
    "temor",
    "ejemplo",
    "bueno",
    "buen",
    "malo",
    "superior",
    "inferior",
    "central",
    "lateral",
    "frontal",
    "trasero",
    "posterior",
    "cierto",
    "real",
    "falso",
    "mayor",
    "menor",
    "importante",
    "necesario",
    "absoluto",
    "relativo",
    "caro",
    "barato",
    "viejo",
    "joven",
    "nuevo",
    "cada",
    "cualquier",
    "dado",
    "actual",
    "reciente",
    "capaz",
    "fácil",
    "simple",
    "sencillo",
    "difícil",
    "complicado",
    "posible",
    "imposible",
    "probable",
    "improbable",
    "estricto",
    "serio",
    "general",
    "particular",
    "común",
    "especial",
    "usual",
    "único",
    "raro",
    "extraño",
    "fuerte",
    "débil",
    "correcto",
    "acertado",
    "incorrecto",
    "desacertado",
    "contrario",
    "opuesto",
    "inverso",
    "igual",
    "diferente",
    "distinto",
    "parecido",
    "similar",
    "otro",
    "diverso",
    "manual",
    "automático",
    "universal",
    "mundial",
    "continental",
    "internacional",
    "nacional",
    "regional",
    "local",
    "urbano",
    "rural",
    "social",
    "político",
    "cultural",
    "artístico",
    "propio",
    "ajeno",
    "público",
    "privado",
    "caliente",
    "frío",
    "ligero",
    "pesado",
    "suave",
    "firme",
    "flexible",
    "duro",
    "blando",
    "caluroso",
    "frío",
    "fresco",
    "delicioso",
    "apetitoso",
    "horrible",
    "dulce",
    "picante",
    "salado",
    "amargo",
    "anterior",
    "posterior",
    "siguiente",
    "cercano",
    "lejano",
    "junto",
    "unido",
    "separado",
    "alejado",
    "feliz",
    "triste",
    "solo",
    "solitario",
    "contento",
    "tranquilo",
    "enojado",
    "enfadado",
    "calmo",
    "agitado",
    "ansioso",
    "interesado",
    "aburrido",
    "encantado",
    "cansado",
    "sorprendido",
    "asustado",
    "atemorizado",
    "doloroso",
    "picante",
    "ardiente",
    "apestoso",
    "maloliente",
    "aparecer",
    "desaparecer",
    "existir",
    "cambiar",
    "crecer",
    "vivir",
    "nacer",
    "morir",
    "ir",
    "venir",
    "volver",
    "partir",
    "llegar",
    "llevar",
    "traer",
    "mover",
    "arrojar",
    "lanzar",
    "coger",
    "agarrar",
    "poner",
    "quitar",
    "sacar",
    "alcanzar",
    "acercar",
    "alejar",
    "lanzar",
    "arrojar",
    "lanzar",
    "coger",
    "agarrar",
    "sujetar",
    "golpear",
    "patear",
    "poner",
    "quitar",
    "sacar",
    "alcanzar",
    "acercar",
    "alejar",
    "recoger",
    "levantar",
    "tomar",
    "pegar",
    "sentir",
    "ver",
    "oír",
    "escuchar",
    "tocar",
    "oler",
    "percibir",
    "amar",
    "querer",
    "desear",
    "odiar",
    "detestar",
    "entristecerse",
    "llorar",
    "reír",
    "enojarse",
    "enfadarse",
    "admirar",
    "alabar",
    "elogiar",
    "alegrarse",
    "encantarse",
    "consolar",
    "interesarse",
    "aburrirse",
    "cansarse",
    "sorprenderse",
    "asustarse",
    "atemorizarse",
    "comunicarse",
    "afirmar",
    "negar",
    "decir",
    "hablar",
    "callar",
    "escribir",
    "leer",
    "analizar",
    "pensar",
    "cantar",
    "señalar",
    "apuñalar",
    "morder",
    "clavar",
    "comer",
    "beber",
    "acordar",
    "afectar",
    "generar",
    "añadir",
    "agregar",
    "mejorar",
    "empeorar",
    "seguir",
    "avanzar",
    "retroceder",
    "ayudar",
    "complicar",
    "reunirse",
    "entrevistar",
    "abrir",
    "desenvolver",
    "jugar",
    "tener",
    "faltar",
    "dar",
    "recibir",
    "romper",
    "doblar",
    "cortar",
    "comprar",
    "vender",
    "llevar puesto",
    "cambiar",
    "intercambiar",
    "sustituir",
    "reemplazar",
    "cerrar",
    "buscar",
    "encontrar",
    "obtener",
    "conseguir",
    "crear",
    "creer",
    "comenzar",
    "iniciar",
    "empezar",
    "terminar",
    "acabar",
    "abandonar",
    "dejar",
    "entrar",
    "quedarse",
    "salir",
    "atender",
    "medir",
    "pesar",
    "considerar",
    "comparar",
    "evaluar",
    "decidir",
    "construir",
    "destruir",
    "deber",
    "poder",
    "conocer",
    "entender",
    "comprender",
    "atar",
    "saber",
    "trabajar",
    "separar",
    "dividir",
    "partir",
    "descansar",
    "dormir",
    "despertar",
    "aceptar",
    "rechazar",
    "descartar",
    "acompañar",
    "pedir",
    "solicitar",
    "pretender",
    "proponer",
    "sugerir",
    "usar",
    "utilizar",
    "hacer",
    "fabricar",
    "arreglar",
    "reparar",
    "explicar",
    "mostrar",
    "tratar",
    "evitar",
    "probar",
    "intentar",
    "comprobar",
    "verificar",
    "variar",
    "esperar",
    "necesitar",
    "precisar",
    "significar",
    "parecer",
    "distinguir"
];